// <auto-generated />
namespace Bonos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806261858188_Add user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
